repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-symlinks
      - id: detect-aws-credentials
      - id: detect-private-key
      - id: forbid-submodules
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-fmt
      - id: go-vet
      - id: go-imports
      - id: go-cyclo
        args: [-over 25]
# TODO: uncomment this one
      - id: go-unit-tests
#      - id: go-build
      - id: go-mod-tidy
